### ISSUE TITLE
Fatal error when Nosto 2.4.0 is installed

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/nostotagging#16]
When the latest version of the module Nosto has been installed, the following error appears on the module list and prevent to load the page properly:
![capture du 2015-06-19 11 32 52](https://cloud.githubusercontent.com/assets/6768917/8250898/f297cdce-1677-11e5-8b59-d4aca293c714.png)

I guess you forgot some `require_once(...)`

**Comment by kryysler** [comment]
Issue is due to bad release package. The repo master branch points to the correct commit of the Nosto SDK, but the download package released to addons.prestashop.com contains the old version. 

Issue has been addressed in PR #17

**Comment by Quetzacoalt91** [comment]
Okay, we can now close this issue
