### ISSUE TITLE
Homepage slots in different positions/hooks

### ISSUE THREAD

**Issue by xbenjii** [PrestaShop/nostotagging#20]
Is there any way to do this without manually inserting tags? For example, I want one slot in the header and one in the footer, but it's not currently possible due to the tags being wrapped in one block

```
<div class="hidden_nosto_element" data-nosto-id="frontpage-nosto-1"></div>
<div class="hidden_nosto_element" data-nosto-id="frontpage-nosto-2"></div>
<div class="hidden_nosto_element" data-nosto-id="frontpage-nosto-3"></div>
<div class="hidden_nosto_element" data-nosto-id="frontpage-nosto-4"></div>
```

**Comment by kryysler** [comment]
The easiest solution is to un-hook the "displayHome" hook, and add the <div> tags manually to your theme where you want them to be displayed. The Prestashop hook system is a bit limited in the sense that you can't place content wherever you want using hooks, unless you create your own custom hooks, but that is effectively the same as just placing the tags in the theme manually. Hope this answers your question.

**Comment by xbenjii** [comment]
Seems easy enough, thanks.
